---
title: Cybeadon
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
description: ''
baseurl: ''
url: https://cybeadon.com
email: cybeadon@gmail.com
permalink: "/blog/:title/"
paginate: 5
paginate_path: "/blog/page/:num/"
logo: ''
author:
  name: Sasivarnan R
  email: sasivarnan36@gmail.com
  twitter: iamsasivarnan
  facebook: iamsasivarnan
  instagram: iamsasivarnan
  github: sasivarnan
  linkedin: sasivarnan
twitter:
  username: cybeadon
social:
  name: Cybeadon
  links:
  - https://twitter.com/cybeadon
  - https://www.facebook.com/cybeadon
  - https://github.com/cybeadon
webmaster_verifications:
  google: jdWkuLCHRn4NeeWcUfnAdh4cGHzoTQdeV5SdTqfkTZo
analytics:
  google: UA-41971011-2
comments:
  disqus: cybeadon
feed:
  path: "/rss/index.xml"
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-gist
- jekyll-archives
- jemoji
exclude:
- Gemfile
- Gemfile.lock
